name: app_simasoft
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.20.1
  just_audio: ^0.9.43
  line_icons: ^2.0.3
  logger: ^2.5.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  timelines_plus: ^1.0.6
  url_launcher: ^6.3.1
  vibration: ^3.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  flutter_animate: ^4.5.2
  another_flushbar: ^1.12.30


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  iconsax_flutter: ^1.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.4
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  giffy_dialog: ^2.3.0
  awesome_dialog: ^3.2.1
  easy_mask: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/animation/
    - assets/audio/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf


